# -*- coding: utf-8 -*-
"""CS6103 Western Math.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbp3yv8__QmAitCOlfb4KeSb1mgZ99g8
"""


from together import Together
import json
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
import sys

typ = sys.argv[1]
prompt_tech = sys.argv[2]
api_key = "YOUR_API_KEY"
client = Together(api_key=api_key)


with open(f"./dataset/{typ}_gsm8k.json", "r", encoding="utf-8") as f:
    train_data = json.load(f)

num_rows = len(train_data)

prompt_dic = {
    "std" : "Answer the question directly. Do not return any preamble, explanation, or reasoning.",
    "cot": "Think step by step to answer the following question. Return the answer at the end of the response after a separator ####."
}

def eval_model(question):
    prompt = f"""
{prompt_dic[prompt_tech]}
Question: {question}
Answer:"""
    cot_eval = client.chat.completions.create(
    model="deepseek-ai/DeepSeek-V3",
    messages=[{"role": "user", "content":prompt}],
    )
    # print(prompt)
    eval_text = cot_eval.choices[0].message.content
    return eval_text

def process_data(i):
    try:
        question = train_data[i]['question']
        org_answer = train_data[i]['answer']
        qid = train_data[i]["qid"]
        response = eval_model(question)
        # print(f"Question {i} Processed")

        return {
            'qid': qid,
            'Question': question,
            'Response': response,
            'Original Answer': org_answer
        }
    except Exception as e:
        print(f"Error processing question {i}: {str(e)}")
        return None

data_list = []
with ThreadPoolExecutor(max_workers=8) as executor:
    futures = [executor.submit(process_data, i) for i in range(num_rows)]

    for future in tqdm(as_completed(futures), total=num_rows):
        result = future.result()
        if result:
            data_list.append(result)

with open(f"results/{typ}_GSMK_{prompt_tech}.json", "w", encoding="utf-8") as f:
    json.dump(data_list, f, indent=4, ensure_ascii=False)

print("JSON file created successfully!")
