# -*- coding: utf-8 -*-
"""cs6103_Translations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ix1XKd45-S0lDXrCTfZEbPz3Byz6CqpC
"""


import json
import csv
from together import Together
from tqdm import tqdm
import re
import concurrent.futures
from functools import partial
import gdown
import sys

data_dic = {
    'hindi': 'https://drive.google.com/uc?id=1uQXLYoNzt_5zT6lVE80i1PYjhLVATlxT',
    'telugu': 'https://drive.google.com/uc?id=1wY4KOP8iWTp0Y_w7STXzLWD36Ynm90e5',
    'oriya': 'https://drive.google.com/uc?id=1PLqvOlsrbxrN4MSWOfMc5gOrRKgP8Xpm'
}

api_key = "YOUR_API_KEY"

# Initialize client once for thread safety
client = Together(api_key=api_key)
lang = sys.argv[1]


gdown.download(data_dic[lang], output=None, quiet=False)

def process_item(source, translation):
    try:
        question = f"Translate the following sentence into {lang}:\n\n{source}\n\nOnly provide the translated sentence. Do not include any explanation or additional text."
        # --- Parallel API calls for answer generation and evaluation
        with concurrent.futures.ThreadPoolExecutor() as executor:
            # Submit answer generation task
            future_answer = executor.submit(
                client.chat.completions.create,
                model="deepseek-ai/DeepSeek-V3",
                messages=[{"role": "user", "content": question}]
            )

            # Submit evaluation task after answer generation completes
            answer_response = future_answer.result()
            answer_text = answer_response.choices[0].message.content

            # Prepare evaluation prompt
            eval_prompt = f"""
                You are a professional bilingual evaluator. Your task is to score a translation generated by a model against a reference translation for both:

                1. **Adequacy** – How well the translation conveys the meaning of the source sentence compared to reference.
                2. **Fluency** – How natural and grammatically correct the sentence is in {lang}. Compare with reference and score.

                Provide your scores on a scale from 0 to 10 for each category and a brief explanation.

                ---

                Source Sentence:
                {source}

                Reference Translation:
                {translation}

                Model Translation:
                {answer_text}

                ---

                Respond in the following format:

                Accuracy: <0–10>
                Fluency: <0-10>
                Explanation: <brief justification>
                """


            future_eval = executor.submit(
                client.chat.completions.create,
                model="deepseek-ai/DeepSeek-V3",
                messages=[{"role": "user", "content": eval_prompt}]
            )

            eval_response = future_eval.result()
            eval_text = eval_response.choices[0].message.content

        # Extract scores (keep your existing extraction logic)
        accuracy_match = re.search(r"Accuracy:\s*(\d+)", eval_text)
        fluency_match = re.search(r"Fluency:\s*(\d+)", eval_text)
        explanation_match = re.search(r"Explanation:\s*(.*)", eval_text, re.DOTALL)

        # Extract values
        accuracy = int(accuracy_match.group(1)) if accuracy_match else None
        fluency = int(fluency_match.group(1)) if fluency_match else None
        explanation = explanation_match.group(1).strip() if explanation_match else ""

        return {
            'Source': source,
            'Translation': translation,
            'Response': answer_text,
            'Justification': explanation,
            'Accuracy': accuracy,
            'Fluency': fluency
        }
    except Exception as e:
        print(f"Error processing question: {str(e)}")
        return None

def main():
    print(f"saving in tscores_{lang}_mann_ki_baat.json")

    data = []
    with open(f'mann_ki_baat_{lang}.csv', 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            data.append((row[0], row[1]))  # (source, model_translation)

    data = data[:1000]
    data_list = []
    max_workers = 8


    with concurrent.futures.ProcessPoolExecutor(max_workers=max_workers) as executor:
        # process_item takes two inputs: source and translation
        process_fn = partial(process_item)

        # Submit all tasks
        futures = [executor.submit(process_fn, src, trans) for src, trans in data]

        for future in tqdm(concurrent.futures.as_completed(futures), total=len(data)):
            result = future.result()
            if result:
                data_list.append(result)

    with open(f"results/tscores_{lang}_mann_ki_baat.json", "w", encoding="utf-8") as f:
        json.dump(data_list, f, indent=4, ensure_ascii=False)

main()

